// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"
)

type Ad struct {
	ID        int32
	AuthorID  int32
	Title     string
	Text      string
	ImageUrl  string
	Price     string
	CreatedAt time.Time
}

type User struct {
	ID           int32
	Username     string
	PasswordHash string
	CreatedAt    time.Time
}
